Controllers/Teacher/MappingController.cs
using SyllabusAutomation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SyllabusAutomation.Controllers.Teacher
{
    public class MappingController : Controller
    {
        // GET: Mapping
        SyllabusAutomationEntities db = new SyllabusAutomationEntities(); // Your database context

        public ActionResult Index()
        {
            var viewModel = new SubjectViewModel
            {
                Subjects = db.Courses.ToList(),
                ClotoploMappings = new List<CLOToPLO>(), // Initialize the list
                IsEditMode = false
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(SubjectViewModel viewModel)
        {
            if (viewModel.SelectedSubjectId != 0)
            {
                viewModel.ClotoploMappings = db.CLOToPLOes.Where(c => c.CourseId == viewModel.SelectedSubjectId).ToList();
            }

            viewModel.Subjects = db.Courses.ToList();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult ToggleEditMode(SubjectViewModel viewModel)
        {
            viewModel.IsEditMode = !viewModel.IsEditMode;

            if (viewModel.SelectedSubjectId != 0)
            {
                viewModel.ClotoploMappings = db.CLOToPLOes.Where(c => c.CourseId == viewModel.SelectedSubjectId).ToList();
            }

            viewModel.Subjects = db.Courses.ToList();

            return View("Index", viewModel);
        }
    }
}

Views/Mapping/Index.cshtml
@model SyllabusAutomation.Models.SubjectViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Select a Subject</h2>

@using (Html.BeginForm("Index", "Mapping", FormMethod.Post))
{
    <div>
        @Html.DropDownListFor(m => m.SelectedSubjectId, new SelectList(Model.Subjects, "CourseId", "CourseTitle"), "-- Select Subject --")
        <input type="submit" value="Show Mapping" />
    </div>
}


    <h3>CLo to PLO Mapping</h3>
    <table>
        <thead>
            <tr>
                <th>CLo</th>
                <th>PLO</th>
            </tr>
        </thead>
        @if (Model.ClotoploMappings.Any())
        {
            <tbody>
                @foreach (var mapping in Model.ClotoploMappings)
                {
                    
                    <tr>
                        <td>@(Model.IsEditMode ? Html.HiddenFor(m => mapping.CLOId) : mapping.CLOId)</td>
                        <td>@(Model.IsEditMode ? Html.HiddenFor(m => mapping.PLOId) : mapping.PLOId)</td>
                    </tr>
                    
                }
            </tbody>
        }
        </table>


@using (Html.BeginForm("ToggleEditMode", "Mapping", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SelectedSubjectId)
    <button type="submit">@((Model.IsEditMode ? "Save" : "Edit") + " Mode")</button>
}